### ISSUE TITLE
Request help for POST invoicing 

### ISSUE THREAD

**Issue by SliiCer** [whitecube/winbooks-on-web-php-client#1]
Hello! 

First, thanks for your repo! It's really appreciated ;)

I just need to POST new invoicing to Winbook when needed..
And i'm wondering if you can provide me a sample of this POST..

I'm a bit confused on "how to use" multiple Models inside Logistics.DocumentHeader Model (DocumentAddressing/DocumentDetail/DocumentRow)

I'm new with Winbook and don't have access to it, i've only the $email and $exchange_token!

Thanks,
Bruno

**Comment by toonvandenbos** [comment]
Hi @SliiCer,

All models are automatically serialized when sent to the API, meaning you can build objects as follows :

```php
$request = [
    // ...
    'Addressing' => new \Whitecube\Winbooks\Models\Logistics\DocumentAddressing([
        // ...
    ]),
    'Details' => [
        new \Whitecube\Winbooks\Models\Logistics\DocumentDetail([
            // ...
            'Row' => new \Whitecube\Winbooks\Models\Logistics\DocumentRow([
                // ...
            ]),
        ]),
        new \Whitecube\Winbooks\Models\Logistics\DocumentDetail([
            // ...
            'Row' => new \Whitecube\Winbooks\Models\Logistics\DocumentRow([
                // ...
            ]),
        ]),
    ],
];

$documentRef = 'something_unique';

$winbooks->add('DocumentHeader', $documentRef, $request);
```

I did not test this yet but it should give you an idea of how to define sub-models. Be aware that some models (e.g. : `\Whitecube\Winbooks\Models\Logistics\DocumentAddressing`) do not exist in this package yet. We add them when we need them (and we had to pause our project due to problems with Winbooks), so please feel free to publish a PR if you need undefined models.

Also, please note that we contacted Winbooks' development team and that they told us they were working on a new API version, which is good news since their current version has a lot of problems. I have no idea how they will transition from one version to the other or if the new version will be better than the current one, but let's hope they will not break compatibility when it happens. Otherwise we'll have to adapt this package, which is not always easy to plan without prior notice.

**Comment by SliiCer** [comment]
Hello @Nyratas, 

Thanks a lot, for all the informations! 
You save my day ;)
